databases:
  - name: three_lines_diary
    databaseName: three_lines_diary
    user: maru973
    region: singapore

services:
  - type: web
    name: three_lines_diary
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: three_lines_diary
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false